### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-ejs#10]
From https://github.com/w3c/wot-thing-description/pull/1151#issuecomment-913621245

- [x] (Kaz) Set up a repo for the new document. Something generic like enveloped-json-signatures; note, not associated with wot. If using wot prefix is required, then it can be wot-enveloped-json-signatures (or how about wot-ejs, since will be easier to share).
- [x] (McCool) Extract the current spec for signatures and put it in a separate document. Will just copy the TD spec, delete everything not related to signatures, make it a W3C (Draft) Note, etc.
- [ ] (McCool) Cleanup, following Oliver's suggestions. In particular, relate explicitly to XML Signatures and JWS, explain motivation, put in tables to compare and map features, etc.  See https://github.com/w3c/wot-ejs/issues/6
- [ ] (Kaz, McCool) Reach out to W3C TAG to discuss.
- [x] (Oliver, McCool) Reach out to IETF, JOSE/COSE/JWS community to get alignment, and converge on a standard. IETF 112 is Nov 6-12, and/or we could invite someone (Carsten Bormann would be good to reach out to) to our F2F.  Update: joint T2TRG/DID call scheduled for Oct 28, will try to also involve COSE members.  See https://github.com/w3c/wot/issues/987
- [ ] We still want implementations for IETF "working code" process. Need at least one to drive discussion at IETF, two if we want to proceed to a W3C REC. Two would be a good idea to test interop even if doing an IETF RFC.
- [ ] Discuss (e.g. at F2F) whether this should go into our next WoT WG charter. McCool's opinion: not critical to be in our charter if our goal is to make it an IETF RFC that we can just cite, then our only action will be to cite it for TD 2.0. For TD 1.x it would be optional/experimental and invokable by using an extension vocabulary.  Update: added note to https://github.com/w3c/wot/issues/978
